site_name: DataRescue Ukraine Workflow
pages:
    - Home: index.md
    - Surveying:
      - Surveying: surveying.md
    - Website Archiving:
      - Seeding: seeding.md
    - Archiving More Complex Datasets:
      - Researching: researching.md
      - Harvesting: harvesting.md
      - Checking/Bagging: bagging.md
      - Describing: describing.md
    - Event Organizing:
      - Before an Event: organizing/pre-event.md
      - After an Event: organizing/post-event.md
    - Additional Resources:
      - Archivers App FAQ: faq.md
extra_css:
    - css/extra.css
theme:
  name: material
  #custom_dir: overrides
  palette:
  - scheme: default
    primary: pink
    accent: blue
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - scheme: slate
    primary: pink
    accent: blue
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo.png
  favicon: img/logo.png
  language: en
repo_name: DataRescue Ukraine
repo_url: https://github.com/DataRescue-Ukraine
